# Generated by Django 4.2.1 on 2023-05-14 19:06

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Имя пользователя')),
                ('email', models.CharField(help_text='Введите вашу электронную почту', max_length=40, unique=True, verbose_name='Электронная почта')),
                ('password', models.CharField(help_text='Введите пароль', max_length=30, verbose_name='Пароль')),
                ('first_name', models.CharField(help_text='Введите ваше имя', max_length=20, verbose_name='Имя')),
                ('second_name', models.CharField(help_text='Введите вашу фамилию', max_length=20, verbose_name='Фамилия')),
                ('last_name', models.CharField(help_text='Введите ваше отчество', max_length=25, verbose_name='Отчество')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите ваше имя', max_length=20, verbose_name='Имя')),
                ('second_name', models.CharField(help_text='Введите вашу фамилию', max_length=20, verbose_name='Фамилия')),
                ('last_name', models.CharField(help_text='Введите ваше отчество', max_length=25, verbose_name='Отчество')),
                ('gender', models.BooleanField(help_text='Выберите ваш пол', verbose_name='Пол')),
                ('birth_date', models.DateField(help_text='Введите дату рождения', verbose_name='Дата рождения')),
                ('email', models.CharField(help_text='Введите вашу электронную почту', max_length=40, verbose_name='Электронная почта')),
                ('username', models.CharField(max_length=20, verbose_name='Имя пользователя')),
                ('password', models.CharField(help_text='Введите пароль', max_length=30, verbose_name='Пароль')),
                ('address', models.CharField(help_text='Введите адрес', max_length=40, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(help_text='Введите телефон', max_length=12, null=True, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите ваше имя', max_length=20, verbose_name='Имя')),
                ('second_name', models.CharField(help_text='Введите вашу фамилию', max_length=20, verbose_name='Фамилия')),
                ('last_name', models.CharField(help_text='Введите ваше отчество', max_length=25, verbose_name='Отчество')),
                ('birth_date', models.DateField(help_text='Введите дату рождения', verbose_name='Дата рождения')),
                ('insurance', models.BigIntegerField(help_text='Введите номер страхового полиса', verbose_name='Страховой полис')),
                ('email', models.CharField(help_text='Введите вашу электронную почту', max_length=40, unique=True, verbose_name='Электронная почта')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Имя пользователя')),
                ('password', models.CharField(help_text='Введите пароль', max_length=30, verbose_name='Пароль')),
                ('address', models.CharField(help_text='Введите адрес', max_length=100, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(help_text='Введите телефон', max_length=12, null=True, verbose_name='Телефон')),
                ('reserve_email', models.CharField(help_text='Введите запасную электронную почту', max_length=40, null=True, verbose_name='Электронная почта')),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите специальность', max_length=30, verbose_name='Специальность')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Выберите дату записи', verbose_name='Дата записи')),
                ('rec_time', models.TimeField(help_text='Выберите время записи', verbose_name='Время записи')),
                ('patient_birth_date', models.DateField(help_text='Введите дату рождения пациента', verbose_name='Дата рождения пациента')),
                ('description', models.CharField(help_text='Опишите проблему', max_length=100, null=True, verbose_name='Описание')),
                ('doctors_name', models.ForeignKey(help_text='Введите инициалы доктора', on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor', verbose_name='Инициалы доктора')),
                ('doctors_speciality', models.ForeignKey(help_text='Введите специальность доктора', null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.speciality', verbose_name='Специальность доктора')),
                ('patient_name', models.ForeignKey(help_text='Выберите пациента', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Инициалы пациента')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='speciality',
            field=models.ForeignKey(help_text='Выберите специальность', null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.speciality', verbose_name='Специальность'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='records',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.record'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
