# Generated by Django 4.2.1 on 2023-05-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(help_text='Введите ваше имя', max_length=20, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(help_text='Введите ваше отчество', max_length=25, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='second_name',
            field=models.CharField(help_text='Введите вашу фамилию', max_length=20, null=True, verbose_name='Фамилия'),
        ),
    ]
