# Generated by Django 4.2.1 on 2023-05-15 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='doctors_speciality',
        ),
        migrations.RemoveField(
            model_name='record',
            name='patient_birth_date',
        ),
        migrations.AddField(
            model_name='record',
            name='patient',
            field=models.ForeignKey(default=1, help_text='Введите ФИО', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пациент'),
            preserve_default=False,
        ),
    ]
